//
// Created by Москалевський on 4/10/17.
//

#include <regex>
#include <boost/algorithm/string/join.hpp>
#include <boost/algorithm/string.hpp>

namespace ufal {
namespace udpipe {
    using std::wstring;
    using std::string;
    using std::wregex;
    using std::regex;
    using std::vector;

    struct PrefixSpec
    {
      wregex re;
      std::function<bool(string& tag)> test_and_postproc;
    };


    static const auto SYM_TAG = "~SYM~";
    static const auto FOREIGN_TAG = "~X~~Foreign=Yes";
    static const auto INTJ_TAG = "~INTJ~";
    static const auto ADV_TAG = "~ADV~";

    static const wregex SMILE_RE(LR"([:;]\(+|[:;]\)+)");
    static const wregex FOREIGN_RE(LR"(.*[a-zA-ZыЫёЁъЪ].*)");
    static const wregex ARABIC_1_2_NUMERAL_RE(LR"((\d+?[^1])?[12])");
    static const wregex ARABIC_GENERAL_NUMERAL_RE(LR"(\d+?1\d|\d+?[03-9])");
    static const wregex ARABIC_NUMERAL_RE(LR"(\d+)");
    static const wregex FRACTION_NUMERAL_RE(LR"(\d+([,\.]\d+)?)");
    // see "B. Parsing a URI Reference with a Regular Expression" http://www.ietf.org/rfc/rfc2396.txt
//  static const std::wregex URL_RE(LR"(^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?)");
    static const wregex URL_LOSE_RE(LR"(https?://.*|www\..*)");

    static const wregex ABBR_NUMERAL_RE{LR"((\d+)[-–—]?([^\d]+))"};


    static const std::map<wstring, wstring> DEFAULT_LEMMAS_MAP{
        {L"колисатися", L"колихатися"},
    };

    const std::vector<std::wstring> INTJ_RE_STRS = {
        LR"(о+)",
        LR"(є+)",
        LR"(а+)",
        LR"(уу+)",
        LR"(ги+)",
        LR"(ммм+)",
        LR"(еее+)",
        LR"(гг+)",
        LR"(фу+)",
        LR"(бу+)",
        LR"(о+к)",
        LR"(юху+)",
        LR"(ура+)",
        LR"(о(ло){2,})",
        LR"(уфф+)",
        LR"(а?(ха)+х?)",
        LR"(і?(хі)+х?)",
    };

    const wregex INTJ_RE{boost::join(INTJ_RE_STRS, L"|")};

    static const wstring GLUED_PREFIXES[]{
        L"авіа",
        L"авто",
        L"агро",
        L"аеро",
        L"анти",
        L"архі",
        L"аудіо",
        L"бензо",
        L"бібліо",
        L"біо",
        L"вело",
        L"вібро",
        L"віце-",
        L"водо",
        L"газо",
        L"геліо",
        L"гео",
        L"гідро",
        L"гіпер",
        L"давньо",
        L"динаміко",
        L"екзо",
        L"екс-",
        L"електро",
        L"етно",
        L"зоо",
        L"ізо",
        L"інтер",
        L"квазі",
        L"контр",
        L"космо",
        L"культ",
        L"лакто",
        L"лже",
        L"макро",
        L"максі",
        L"мед",
        L"мега",
        L"мета",
        L"метео",
        L"мікро",
        L"міні",
        L"моно",
        L"мото",
        L"мульти",
        L"нео",
        L"пост",
        L"пост-",
        L"псевдо",
        L"радіо",
        L"спец",
        L"стерео",
        L"супер",
        L"теле",
        L"телерадіо",
        L"транс",
        L"турбо",
        L"ультра",
        L"фіз",
        L"фото",
    };

    static const wstring VERB_PREFECTION_PREFIXES[]{
        L"обі",
        L"від",
        L"об",
        L"по",
        L"роз",
        L"за",
        L"з",
        L"у",
        L"пере",
        L"ви",
        L"на",
        L"пови",
        L"про",
    };

    static const wstring ADJ_PREFIXES[]{
        L"не",
        L"між",
        L"недо",
        L"поза",
        L"по",
        L"пів",
        L"напів",
        L"мало",
    };

    const wregex PREFIX_1_RE{L"^(" + boost::join(GLUED_PREFIXES, L"|") + L")+"};
    const wregex VERB_PREFECTION_PREFIXES_RE{L"^(" + boost::join(VERB_PREFECTION_PREFIXES, L"|") + L")+"};
    const wregex ADJ_PREFIXES_RE{L"^(" + boost::join(ADJ_PREFIXES, L"|") + L")+"};


    static const PrefixSpec PREFIX_SPECS[]{
        {wregex(L"^пів"),                                  [](string& tag) {
          return boost::contains(tag, "~NOUN~");
        }},
        {ADJ_PREFIXES_RE, [](string& tag) {
          return boost::contains(tag, "~ADJ~");
        }},
        {PREFIX_1_RE,                                      [](string& tag) {
          static const regex re("~(NOUN|ADJ|ADV)~");
          return std::regex_search(tag, re);
        }},
        {VERB_PREFECTION_PREFIXES_RE,                      [](string& tag) {
          static const regex re("~VERB~~.*Aspect=Imp");
          if (!std::regex_search(tag, re)) {
            return false;
          }
          boost::replace_first(tag, "Aspect=Imp", "Aspect=Perf");
          if (boost::contains(tag, "Tense=Pres")) {
            boost::replace_first(tag, "Tense=Pres", "Tense=Fut");
          }
          return true;
        }},
    };

    static const auto DIGITAL_1_2_PARADIGM = {
        "~NUM~~Case=Nom|Gender=Masc|NumType=Card",
        "~NUM~~Case=Gen|Gender=Masc|NumType=Card",
        "~NUM~~Case=Dat|Gender=Masc|NumType=Card",
        "~NUM~~Case=Acc|Gender=Masc|NumType=Card",
        "~NUM~~Case=Ins|Gender=Masc|NumType=Card",
        "~NUM~~Case=Loc|Gender=Masc|NumType=Card",
        "~NUM~~Case=Voc|Gender=Masc|NumType=Card",
        "~NUM~~Case=Nom|Gender=Fem|NumType=Card",
        "~NUM~~Case=Gen|Gender=Fem|NumType=Card",
        "~NUM~~Case=Dat|Gender=Fem|NumType=Card",
        "~NUM~~Case=Acc|Gender=Fem|NumType=Card",
        "~NUM~~Case=Ins|Gender=Fem|NumType=Card",
        "~NUM~~Case=Loc|Gender=Fem|NumType=Card",
        "~NUM~~Case=Voc|Gender=Fem|NumType=Card",
        "~NUM~~Case=Nom|Gender=Neut|NumType=Card",
        "~NUM~~Case=Gen|Gender=Neut|NumType=Card",
        "~NUM~~Case=Dat|Gender=Neut|NumType=Card",
        "~NUM~~Case=Acc|Gender=Neut|NumType=Card",
        "~NUM~~Case=Ins|Gender=Neut|NumType=Card",
        "~NUM~~Case=Loc|Gender=Neut|NumType=Card",
        "~NUM~~Case=Voc|Gender=Neut|NumType=Card",
    };

    static const auto DIGITAL_GENERAL_PARADIGM = {
        "~NUM~~Case=Nom|Number=Plur|NumType=Card",
        "~NUM~~Case=Gen|Number=Plur|NumType=Card",
        "~NUM~~Case=Dat|Number=Plur|NumType=Card",
        "~NUM~~Case=Acc|Number=Plur|NumType=Card",
        "~NUM~~Case=Ins|Number=Plur|NumType=Card",
        "~NUM~~Case=Loc|Number=Plur|NumType=Card",
        "~NUM~~Case=Voc|Number=Plur|NumType=Card",
    };

    static const auto DIGITAL_COMMON_PARADIGM = {
        "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Acc|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord",
        "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord",
        "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord",
        "~ADJ~~Case=Nom|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Gen|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Dat|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Acc|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Ins|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Loc|Number=Plur|NumType=Ord",
        "~ADJ~~Case=Voc|Number=Plur|NumType=Ord",
//    };
//
//    static const auto ORDINAL_ASNOUN_PARADIGM = {
        "~NOUN~~Animacy=Inan|Case=Nom|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Gen|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Dat|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Acc|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Ins|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Loc|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Voc|Gender=Masc",
        "~NOUN~~Animacy=Inan|Case=Nom|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Gen|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Dat|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Acc|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Ins|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Loc|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Voc|Gender=Fem",
        "~NOUN~~Animacy=Inan|Case=Nom|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Gen|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Dat|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Acc|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Ins|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Loc|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Voc|Gender=Neut",
        "~NOUN~~Animacy=Inan|Case=Nom|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Gen|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Dat|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Acc|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Ins|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Loc|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Voc|Number=Plur",
        "~NOUN~~Animacy=Inan|Case=Nom|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Gen|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Dat|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Acc|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Ins|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Loc|Number=Ptan",
        "~NOUN~~Animacy=Inan|Case=Voc|Number=Ptan",
    };

    struct NumMapRow
    {
      wchar_t digit;
      wstring form;
      wstring lemma;
      string tag;
    };
    static const NumMapRow NUMERAL_MAP[] = {
        {L'1', L"перший",      L"перший",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'1', L"першого",     L"перший",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'1', L"першому",     L"перший",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'1', L"першого",     L"перший",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'1', L"перший",      L"перший",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'1', L"першим",      L"перший",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'1', L"першім",      L"перший",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'1', L"першому",     L"перший",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'1', L"перший",      L"перший",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'1', L"перша",       L"перший",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'1', L"першая",      L"перший",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'1', L"першої",      L"перший",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'1', L"першій",      L"перший",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'1', L"першу",       L"перший",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'1', L"першую",      L"перший",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'1', L"першою",      L"перший",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'1', L"першій",      L"перший",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'1', L"перша",       L"перший",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'1', L"першая",      L"перший",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'1', L"перше",       L"перший",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'1', L"першеє",      L"перший",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'1', L"першого",     L"перший",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'1', L"першому",     L"перший",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'1', L"перше",       L"перший",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'1', L"першеє",      L"перший",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'1', L"першим",      L"перший",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'1', L"першім",      L"перший",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'1', L"першому",     L"перший",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'1', L"перше",       L"перший",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'1', L"першеє",      L"перший",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'1', L"перші",       L"перший",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'1', L"першії",      L"перший",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'1', L"перших",      L"перший",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'1', L"першим",      L"перший",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'1', L"перших",      L"перший",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'1', L"перші",       L"перший",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'1', L"першії",      L"перший",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'1', L"першими",     L"перший",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'1', L"перших",      L"перший",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'1', L"перші",       L"перший",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'1', L"першії",      L"перший",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другий",      L"другий",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'2', L"другого",     L"другий",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'2', L"другому",     L"другий",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'2', L"другого",     L"другий",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'2', L"другий",      L"другий",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'2', L"другим",      L"другий",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'2', L"другім",      L"другий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'2', L"другому",     L"другий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'2', L"другий",      L"другий",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'2', L"друга",       L"другий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'2', L"другая",      L"другий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другої",      L"другий",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'2', L"другій",      L"другий",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'2', L"другу",       L"другий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'2', L"другую",      L"другий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другою",      L"другий",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'2', L"другій",      L"другий",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'2', L"друга",       L"другий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'2', L"другая",      L"другий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'2', L"друге",       L"другий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'2', L"другеє",      L"другий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другого",     L"другий",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'2', L"другому",     L"другий",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'2', L"друге",       L"другий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'2', L"другеє",      L"другий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другим",      L"другий",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'2', L"другім",      L"другий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'2', L"другому",     L"другий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'2', L"друге",       L"другий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'2', L"другеє",      L"другий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другі",       L"другий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'2', L"другії",      L"другий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'2', L"других",      L"другий",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'2', L"другим",      L"другий",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'2', L"других",      L"другий",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'2', L"другі",       L"другий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'2', L"другії",      L"другий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'2', L"другими",     L"другий",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'2', L"других",      L"другий",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'2', L"другі",       L"другий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'2', L"другії",      L"другий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третій",      L"третій",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'3', L"третього",    L"третій",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'3', L"третьому",    L"третій",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'3', L"третього",    L"третій",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'3', L"третій",      L"третій",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'3', L"третім",      L"третій",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'3', L"третім",      L"третій",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'3', L"третьому",    L"третій",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'3', L"третій",      L"третій",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'3', L"третя",       L"третій",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'3', L"третяя",      L"третій",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третьої",     L"третій",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'3', L"третій",      L"третій",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'3', L"третю",       L"третій",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'3', L"третюю",      L"третій",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третьою",     L"третій",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'3', L"третій",      L"третій",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'3', L"третя",       L"третій",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'3', L"третяя",      L"третій",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третє",       L"третій",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'3', L"третєє",      L"третій",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третього",    L"третій",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'3', L"третьому",    L"третій",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'3', L"третє",       L"третій",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'3', L"третєє",      L"третій",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третім",      L"третій",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'3', L"третім",      L"третій",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'3', L"третьому",    L"третій",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'3', L"третє",       L"третій",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'3', L"третєє",      L"третій",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'3', L"треті",       L"третій",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'3', L"третії",      L"третій",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третіх",      L"третій",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'3', L"третім",      L"третій",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'3', L"третіх",      L"третій",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'3', L"треті",       L"третій",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'3', L"третії",      L"третій",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'3', L"третіми",     L"третій",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'3', L"третіх",      L"третій",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'3', L"треті",       L"третій",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'3', L"третії",      L"третій",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертий",   L"четвертий", "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертого",  L"четвертий", "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертому",  L"четвертий", "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертого",  L"четвертий", "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертий",   L"четвертий", "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертим",   L"четвертий", "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертім",   L"четвертий", "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертому",  L"четвертий", "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'4', L"четвертий",   L"четвертий", "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'4', L"четверта",    L"четвертий", "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'4', L"четвертая",   L"четвертий", "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертої",   L"четвертий", "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'4', L"четвертій",   L"четвертий", "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'4', L"четверту",    L"четвертий", "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'4', L"четвертую",   L"четвертий", "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертою",   L"четвертий", "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'4', L"четвертій",   L"четвертий", "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'4', L"четверта",    L"четвертий", "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'4', L"четвертая",   L"четвертий", "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четверте",    L"четвертий", "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертеє",   L"четвертий", "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертого",  L"четвертий", "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертому",  L"четвертий", "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'4', L"четверте",    L"четвертий", "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертеє",   L"четвертий", "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертим",   L"четвертий", "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертім",   L"четвертий", "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертому",  L"четвертий", "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'4', L"четверте",    L"четвертий", "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'4', L"четвертеє",   L"четвертий", "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четверті",    L"четвертий", "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'4', L"четвертії",   L"четвертий", "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертих",   L"четвертий", "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'4', L"четвертим",   L"четвертий", "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'4', L"четвертих",   L"четвертий", "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'4', L"четверті",    L"четвертий", "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'4', L"четвертії",   L"четвертий", "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'4', L"четвертими",  L"четвертий", "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'4', L"четвертих",   L"четвертий", "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'4', L"четверті",    L"четвертий", "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'4', L"четвертії",   L"четвертий", "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятий",      L"п’ятий",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятого",     L"п’ятий",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятому",     L"п’ятий",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятого",     L"п’ятий",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятий",      L"п’ятий",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятим",      L"п’ятий",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятім",      L"п’ятий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятому",     L"п’ятий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ятий",      L"п’ятий",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'5', L"п’ята",       L"п’ятий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ятая",      L"п’ятий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятої",      L"п’ятий",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ятій",      L"п’ятий",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'5', L"п’яту",       L"п’ятий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ятую",      L"п’ятий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятою",      L"п’ятий",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ятій",      L"п’ятий",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ята",       L"п’ятий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'5', L"п’ятая",      L"п’ятий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’яте",       L"п’ятий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятеє",      L"п’ятий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятого",     L"п’ятий",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятому",     L"п’ятий",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'5', L"п’яте",       L"п’ятий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятеє",      L"п’ятий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятим",      L"п’ятий",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятім",      L"п’ятий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятому",     L"п’ятий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'5', L"п’яте",       L"п’ятий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'5', L"п’ятеє",      L"п’ятий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’яті",       L"п’ятий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятії",      L"п’ятий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятих",      L"п’ятий",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятим",      L"п’ятий",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятих",      L"п’ятий",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'5', L"п’яті",       L"п’ятий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятії",      L"п’ятий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'5', L"п’ятими",     L"п’ятий",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятих",      L"п’ятий",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'5', L"п’яті",       L"п’ятий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'5', L"п’ятії",      L"п’ятий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостий",      L"шостий",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'6', L"шостого",     L"шостий",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'6', L"шостому",     L"шостий",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'6', L"шостого",     L"шостий",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'6', L"шостий",      L"шостий",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'6', L"шостим",      L"шостий",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'6', L"шостім",      L"шостий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'6', L"шостому",     L"шостий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'6', L"шостий",      L"шостий",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'6', L"шоста",       L"шостий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'6', L"шостая",      L"шостий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостої",      L"шостий",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'6', L"шостій",      L"шостий",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'6', L"шосту",       L"шостий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'6', L"шостую",      L"шостий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостою",      L"шостий",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'6', L"шостій",      L"шостий",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'6', L"шоста",       L"шостий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'6', L"шостая",      L"шостий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шосте",       L"шостий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'6', L"шостеє",      L"шостий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостого",     L"шостий",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'6', L"шостому",     L"шостий",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'6', L"шосте",       L"шостий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'6', L"шостеє",      L"шостий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостим",      L"шостий",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'6', L"шостім",      L"шостий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'6', L"шостому",     L"шостий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'6', L"шосте",       L"шостий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'6', L"шостеє",      L"шостий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шості",       L"шостий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'6', L"шостії",      L"шостий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостих",      L"шостий",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'6', L"шостим",      L"шостий",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'6', L"шостих",      L"шостий",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'6', L"шості",       L"шостий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'6', L"шостії",      L"шостий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'6', L"шостими",     L"шостий",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'6', L"шостих",      L"шостий",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'6', L"шості",       L"шостий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'6', L"шостії",      L"шостий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомий",      L"сьомий",    "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомого",     L"сьомий",    "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомому",     L"сьомий",    "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомого",     L"сьомий",    "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомий",      L"сьомий",    "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомим",      L"сьомий",    "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомім",      L"сьомий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомому",     L"сьомий",    "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'7', L"сьомий",      L"сьомий",    "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'7', L"сьома",       L"сьомий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'7', L"сьомая",      L"сьомий",    "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомої",      L"сьомий",    "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'7', L"сьомій",      L"сьомий",    "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'7', L"сьому",       L"сьомий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'7', L"сьомую",      L"сьомий",    "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомою",      L"сьомий",    "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'7', L"сьомій",      L"сьомий",    "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'7', L"сьома",       L"сьомий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'7', L"сьомая",      L"сьомий",    "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьоме",       L"сьомий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомеє",      L"сьомий",    "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомого",     L"сьомий",    "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомому",     L"сьомий",    "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'7', L"сьоме",       L"сьомий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомеє",      L"сьомий",    "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомим",      L"сьомий",    "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомім",      L"сьомий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомому",     L"сьомий",    "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'7', L"сьоме",       L"сьомий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'7', L"сьомеє",      L"сьомий",    "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомі",       L"сьомий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'7', L"сьомії",      L"сьомий",    "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомих",      L"сьомий",    "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'7', L"сьомим",      L"сьомий",    "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'7', L"сьомих",      L"сьомий",    "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'7', L"сьомі",       L"сьомий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'7', L"сьомії",      L"сьомий",    "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'7', L"сьомими",     L"сьомий",    "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'7', L"сьомих",      L"сьомий",    "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'7', L"сьомі",       L"сьомий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'7', L"сьомії",      L"сьомий",    "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмий",     L"восьмий",   "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмого",    L"восьмий",   "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмому",    L"восьмий",   "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмого",    L"восьмий",   "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмий",     L"восьмий",   "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмим",     L"восьмий",   "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмім",     L"восьмий",   "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмому",    L"восьмий",   "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'8', L"восьмий",     L"восьмий",   "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'8', L"восьма",      L"восьмий",   "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'8', L"восьмая",     L"восьмий",   "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмої",     L"восьмий",   "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'8', L"восьмій",     L"восьмий",   "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'8', L"восьму",      L"восьмий",   "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'8', L"восьмую",     L"восьмий",   "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмою",     L"восьмий",   "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'8', L"восьмій",     L"восьмий",   "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'8', L"восьма",      L"восьмий",   "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'8', L"восьмая",     L"восьмий",   "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьме",      L"восьмий",   "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмеє",     L"восьмий",   "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмого",    L"восьмий",   "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмому",    L"восьмий",   "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'8', L"восьме",      L"восьмий",   "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмеє",     L"восьмий",   "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмим",     L"восьмий",   "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмім",     L"восьмий",   "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмому",    L"восьмий",   "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'8', L"восьме",      L"восьмий",   "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'8', L"восьмеє",     L"восьмий",   "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмі",      L"восьмий",   "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'8', L"восьмії",     L"восьмий",   "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмих",     L"восьмий",   "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'8', L"восьмим",     L"восьмий",   "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'8', L"восьмих",     L"восьмий",   "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'8', L"восьмі",      L"восьмий",   "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'8', L"восьмії",     L"восьмий",   "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'8', L"восьмими",    L"восьмий",   "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'8', L"восьмих",     L"восьмий",   "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'8', L"восьмі",      L"восьмий",   "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'8', L"восьмії",     L"восьмий",   "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятий",    L"дев’ятий",  "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятого",   L"дев’ятий",  "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятому",   L"дев’ятий",  "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятого",   L"дев’ятий",  "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятий",    L"дев’ятий",  "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятим",    L"дев’ятий",  "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятім",    L"дев’ятий",  "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятому",   L"дев’ятий",  "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ятий",    L"дев’ятий",  "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'9', L"дев’ята",     L"дев’ятий",  "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ятая",    L"дев’ятий",  "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятої",    L"дев’ятий",  "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ятій",    L"дев’ятий",  "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’яту",     L"дев’ятий",  "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ятую",    L"дев’ятий",  "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятою",    L"дев’ятий",  "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ятій",    L"дев’ятий",  "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ята",     L"дев’ятий",  "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'9', L"дев’ятая",    L"дев’ятий",  "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’яте",     L"дев’ятий",  "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятеє",    L"дев’ятий",  "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятого",   L"дев’ятий",  "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятому",   L"дев’ятий",  "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’яте",     L"дев’ятий",  "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятеє",    L"дев’ятий",  "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятим",    L"дев’ятий",  "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятім",    L"дев’ятий",  "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятому",   L"дев’ятий",  "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’яте",     L"дев’ятий",  "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'9', L"дев’ятеє",    L"дев’ятий",  "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’яті",     L"дев’ятий",  "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятії",    L"дев’ятий",  "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятих",    L"дев’ятий",  "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятим",    L"дев’ятий",  "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятих",    L"дев’ятий",  "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'9', L"дев’яті",     L"дев’ятий",  "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятії",    L"дев’ятий",  "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'9', L"дев’ятими",   L"дев’ятий",  "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятих",    L"дев’ятий",  "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'9', L"дев’яті",     L"дев’ятий",  "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'9', L"дев’ятії",    L"дев’ятий",  "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятий",     L"десятий",   "~ADJ~~Case=Nom|Gender=Masc|NumType=Ord"},
        {L'0', L"десятого",    L"десятий",   "~ADJ~~Case=Gen|Gender=Masc|NumType=Ord"},
        {L'0', L"десятому",    L"десятий",   "~ADJ~~Case=Dat|Gender=Masc|NumType=Ord"},
        {L'0', L"десятого",    L"десятий",   "~ADJ~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'0', L"десятий",     L"десятий",   "~ADJ~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Ord"},
        {L'0', L"десятим",     L"десятий",   "~ADJ~~Case=Ins|Gender=Masc|NumType=Ord"},
        {L'0', L"десятім",     L"десятий",   "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'0', L"десятому",    L"десятий",   "~ADJ~~Case=Loc|Gender=Masc|NumType=Ord"},
        {L'0', L"десятий",     L"десятий",   "~ADJ~~Case=Voc|Gender=Masc|NumType=Ord"},
        {L'0', L"десята",      L"десятий",   "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord"},
        {L'0', L"десятая",     L"десятий",   "~ADJ~~Case=Nom|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятої",     L"десятий",   "~ADJ~~Case=Gen|Gender=Fem|NumType=Ord"},
        {L'0', L"десятій",     L"десятий",   "~ADJ~~Case=Dat|Gender=Fem|NumType=Ord"},
        {L'0', L"десяту",      L"десятий",   "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord"},
        {L'0', L"десятую",     L"десятий",   "~ADJ~~Case=Acc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятою",     L"десятий",   "~ADJ~~Case=Ins|Gender=Fem|NumType=Ord"},
        {L'0', L"десятій",     L"десятий",   "~ADJ~~Case=Loc|Gender=Fem|NumType=Ord"},
        {L'0', L"десята",      L"десятий",   "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord"},
        {L'0', L"десятая",     L"десятий",   "~ADJ~~Case=Voc|Gender=Fem|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десяте",      L"десятий",   "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord"},
        {L'0', L"десятеє",     L"десятий",   "~ADJ~~Case=Nom|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятого",    L"десятий",   "~ADJ~~Case=Gen|Gender=Neut|NumType=Ord"},
        {L'0', L"десятому",    L"десятий",   "~ADJ~~Case=Dat|Gender=Neut|NumType=Ord"},
        {L'0', L"десяте",      L"десятий",   "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord"},
        {L'0', L"десятеє",     L"десятий",   "~ADJ~~Case=Acc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятим",     L"десятий",   "~ADJ~~Case=Ins|Gender=Neut|NumType=Ord"},
        {L'0', L"десятім",     L"десятий",   "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'0', L"десятому",    L"десятий",   "~ADJ~~Case=Loc|Gender=Neut|NumType=Ord"},
        {L'0', L"десяте",      L"десятий",   "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord"},
        {L'0', L"десятеє",     L"десятий",   "~ADJ~~Case=Voc|Gender=Neut|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десяті",      L"десятий",   "~ADJ~~Case=Nom|Number=Plur|NumType=Ord"},
        {L'0', L"десятії",     L"десятий",   "~ADJ~~Case=Nom|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятих",     L"десятий",   "~ADJ~~Case=Gen|Number=Plur|NumType=Ord"},
        {L'0', L"десятим",     L"десятий",   "~ADJ~~Case=Dat|Number=Plur|NumType=Ord"},
        {L'0', L"десятих",     L"десятий",   "~ADJ~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Ord"},
        {L'0', L"десяті",      L"десятий",   "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord"},
        {L'0', L"десятії",     L"десятий",   "~ADJ~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'0', L"десятими",    L"десятий",   "~ADJ~~Case=Ins|Number=Plur|NumType=Ord"},
        {L'0', L"десятих",     L"десятий",   "~ADJ~~Case=Loc|Number=Plur|NumType=Ord"},
        {L'0', L"десяті",      L"десятий",   "~ADJ~~Case=Voc|Number=Plur|NumType=Ord"},
        {L'0', L"десятії",     L"десятий",   "~ADJ~~Case=Voc|Number=Plur|NumType=Ord|Variant=Uncontr"},
        {L'1', L"один",        L"один",      "~NUM~~Case=Nom|Gender=Masc|NumType=Card"},
        {L'1', L"одного",      L"один",      "~NUM~~Case=Gen|Gender=Masc|NumType=Card"},
        {L'1', L"одному",      L"один",      "~NUM~~Case=Dat|Gender=Masc|NumType=Card"},
        {L'1', L"одного",      L"один",      "~NUM~~Animacy=Anim|Case=Acc|Gender=Masc|NumType=Card"},
        {L'1', L"один",        L"один",      "~NUM~~Animacy=Inan|Case=Acc|Gender=Masc|NumType=Card"},
        {L'1', L"одним",       L"один",      "~NUM~~Case=Ins|Gender=Masc|NumType=Card"},
        {L'1', L"однім",       L"один",      "~NUM~~Case=Loc|Gender=Masc|NumType=Card"},
        {L'1', L"одному",      L"один",      "~NUM~~Case=Loc|Gender=Masc|NumType=Card"},
        {L'1', L"одна",        L"один",      "~NUM~~Case=Nom|Gender=Fem|NumType=Card"},
        {L'1', L"однієї",      L"один",      "~NUM~~Case=Gen|Gender=Fem|NumType=Card"},
        {L'1', L"одної",       L"один",      "~NUM~~Case=Gen|Gender=Fem|NumType=Card"},
        {L'1', L"одній",       L"один",      "~NUM~~Case=Dat|Gender=Fem|NumType=Card"},
        {L'1', L"одну",        L"один",      "~NUM~~Case=Acc|Gender=Fem|NumType=Card"},
        {L'1', L"однією",      L"один",      "~NUM~~Case=Ins|Gender=Fem|NumType=Card"},
        {L'1', L"одною",       L"один",      "~NUM~~Case=Ins|Gender=Fem|NumType=Card"},
        {L'1', L"одній",       L"один",      "~NUM~~Case=Loc|Gender=Fem|NumType=Card"},
        {L'1', L"одне",        L"один",      "~NUM~~Case=Nom|Gender=Neut|NumType=Card"},
        {L'1', L"одно",        L"один",      "~NUM~~Case=Nom|Gender=Neut|NumType=Card"},
        {L'1', L"одного",      L"один",      "~NUM~~Case=Gen|Gender=Neut|NumType=Card"},
        {L'1', L"одному",      L"один",      "~NUM~~Case=Dat|Gender=Neut|NumType=Card"},
        {L'1', L"одне",        L"один",      "~NUM~~Case=Acc|Gender=Neut|NumType=Card"},
        {L'1', L"одно",        L"один",      "~NUM~~Case=Acc|Gender=Neut|NumType=Card"},
        {L'1', L"одним",       L"один",      "~NUM~~Case=Ins|Gender=Neut|NumType=Card"},
        {L'1', L"однім",       L"один",      "~NUM~~Case=Loc|Gender=Neut|NumType=Card"},
        {L'1', L"одному",      L"один",      "~NUM~~Case=Loc|Gender=Neut|NumType=Card"},
        {L'1', L"одні",        L"один",      "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'1', L"одних",       L"один",      "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'1', L"одним",       L"один",      "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'1', L"одних",       L"один",      "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'1', L"одних",       L"один",      "~NUM~~Animacy=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'1', L"одні",        L"один",      "~NUM~~Animacy=Inan|Case=Acc|Number=Plur|NumType=Card"},
        {L'1', L"одними",      L"один",      "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'1', L"одних",       L"один",      "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'2', L"два",         L"два",       "~NUM~~Case=Nom|Gender=Masc|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Gen|Gender=Masc|NumType=Card"},
        {L'2', L"двом",        L"два",       "~NUM~~Case=Dat|Gender=Masc|NumType=Card"},
        {L'2', L"два",         L"два",       "~NUM~~Case=Acc|Gender=Masc|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Acc|Gender=Masc|NumType=Card"},
        {L'2', L"двома",       L"два",       "~NUM~~Case=Ins|Gender=Masc|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Loc|Gender=Masc|NumType=Card"},
        {L'2', L"дві",         L"два",       "~NUM~~Case=Nom|Gender=Fem|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Gen|Gender=Fem|NumType=Card"},
        {L'2', L"двом",        L"два",       "~NUM~~Case=Dat|Gender=Fem|NumType=Card"},
        {L'2', L"дві",         L"два",       "~NUM~~Case=Acc|Gender=Fem|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Acc|Gender=Fem|NumType=Card"},
        {L'2', L"двома",       L"два",       "~NUM~~Case=Ins|Gender=Fem|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Loc|Gender=Fem|NumType=Card"},
        {L'2', L"два",         L"два",       "~NUM~~Case=Nom|Gender=Neut|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Gen|Gender=Neut|NumType=Card"},
        {L'2', L"двом",        L"два",       "~NUM~~Case=Dat|Gender=Neut|NumType=Card"},
        {L'2', L"два",         L"два",       "~NUM~~Case=Acc|Gender=Neut|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Acc|Gender=Neut|NumType=Card"},
        {L'2', L"двома",       L"два",       "~NUM~~Case=Ins|Gender=Neut|NumType=Card"},
        {L'2', L"двох",        L"два",       "~NUM~~Case=Loc|Gender=Neut|NumType=Card"},
        {L'3', L"три",         L"три",       "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'3', L"трьох",       L"три",       "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'3', L"трьом",       L"три",       "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'3', L"три",         L"три",       "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'3', L"трьох",       L"три",       "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'3', L"трьома",      L"три",       "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'3', L"трьох",       L"три",       "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'4', L"чотири",      L"чотири",    "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'4', L"чотирьох",    L"чотири",    "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'4', L"чотирьом",    L"чотири",    "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'4', L"чотири",      L"чотири",    "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'4', L"чотирьох",    L"чотири",    "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'4', L"чотирма",     L"чотири",    "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'4', L"чотирьох",    L"чотири",    "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'5', L"п’ять",       L"п’ять",     "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'5', L"п’яти",       L"п’ять",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьох",     L"п’ять",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'5', L"п’яти",       L"п’ять",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьом",     L"п’ять",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'5', L"п’яти",       L"п’ять",     "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьох",     L"п’ять",     "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'5', L"п’ять",       L"п’ять",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьох",     L"п’ять",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьма",     L"п’ять",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьома",    L"п’ять",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'5', L"п’яти",       L"п’ять",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'5', L"п’ятьох",     L"п’ять",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'6', L"шість",       L"шість",     "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'6', L"шести",       L"шість",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'6', L"шістьох",     L"шість",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'6', L"шести",       L"шість",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'6', L"шістьом",     L"шість",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'6', L"шість",       L"шість",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'6', L"шістьох",     L"шість",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'6', L"шістьма",     L"шість",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'6', L"шістьома",    L"шість",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'6', L"шести",       L"шість",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'6', L"шістьох",     L"шість",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'7', L"сім",         L"сім",       "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'7', L"семи",        L"сім",       "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'7', L"сімох",       L"сім",       "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'7', L"семи",        L"сім",       "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'7', L"сімом",       L"сім",       "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'7', L"сім",         L"сім",       "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'7', L"сімох",       L"сім",       "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'7', L"сімома",      L"сім",       "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'7', L"сьома",       L"сім",       "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'7', L"семи",        L"сім",       "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'7', L"сімох",       L"сім",       "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'8', L"вісім",       L"вісім",     "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'8', L"вісьмох",     L"вісім",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'8', L"восьми",      L"вісім",     "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'8', L"вісьмом",     L"вісім",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'8', L"восьми",      L"вісім",     "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'8', L"вісім",       L"вісім",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'8', L"вісьмох",     L"вісім",     "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'8', L"вісьма",      L"вісім",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'8', L"вісьмома",    L"вісім",     "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'8', L"вісьмох",     L"вісім",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'8', L"восьми",      L"вісім",     "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ять",     L"дев’ять",   "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'9', L"дев’яти",     L"дев’ять",   "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьох",   L"дев’ять",   "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'9', L"дев’яти",     L"дев’ять",   "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьом",   L"дев’ять",   "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'9', L"дев’яти",     L"дев’ять",   "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьох",   L"дев’ять",   "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ять",     L"дев’ять",   "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьох",   L"дев’ять",   "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьма",   L"дев’ять",   "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьома",  L"дев’ять",   "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'9', L"дев’яти",     L"дев’ять",   "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'9', L"дев’ятьох",   L"дев’ять",   "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'0', L"десять",      L"десять",    "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'0', L"десяти",      L"десять",    "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'0', L"десятьох",    L"десять",    "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'0', L"десяти",      L"десять",    "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'0', L"десятьом",    L"десять",    "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'0', L"десяти",      L"десять",    "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"десятьох",    L"десять",    "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"десять",      L"десять",    "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"десятьох",    L"десять",    "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"десятьма",    L"десять",    "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'0', L"десятьома",   L"десять",    "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'0', L"десяти",      L"десять",    "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'0', L"десятьох",    L"десять",    "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'0', L"двадцять",    L"двадцять",  "~NUM~~Case=Nom|Number=Plur|NumType=Card"},
        {L'0', L"двадцяти",    L"двадцять",  "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьох",  L"двадцять",  "~NUM~~Case=Gen|Number=Plur|NumType=Card"},
        {L'0', L"двадцяти",    L"двадцять",  "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьом",  L"двадцять",  "~NUM~~Case=Dat|Number=Plur|NumType=Card"},
        {L'0', L"двадцяти",    L"двадцять",  "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьох",  L"двадцять",  "~NUM~~Animacy[gram]=Anim|Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"двадцять",    L"двадцять",  "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьох",  L"двадцять",  "~NUM~~Case=Acc|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьма",  L"двадцять",  "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьома", L"двадцять",  "~NUM~~Case=Ins|Number=Plur|NumType=Card"},
        {L'0', L"двадцяти",    L"двадцять",  "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
        {L'0', L"двадцятьох",  L"двадцять",  "~NUM~~Case=Loc|Number=Plur|NumType=Card"},
    };
} // namespace udpipe
} // namespace ufal
